type = 'Ranged'

#Weapon Details
[weapon]
name = 'Laser'
flavor_text = 'I couldnt come up with anything clever to go here'

#Technical Specifications

[attack_info]
attach_point = 'right hand'
ammo = 100 #if laser beam, then -5 ammo. If held down, then -1 every 1.47 seconds
attack_template = 'line'
projectile_spawn_location = 0 #grids in front of you
attack_radius = [1, 1, 0] # height and width 
can_move = true
can_charge = true #it just continues to fire if held down, or it fires a single laser beam. 
invulnerable_during = false
terrain_destructor = true
projectile_dmg = 5 #per second of being hit
collision_dmg = 5
velocity = 2 #meters per second? 

[effects]
particle_effect = 'laser'
sfx_on_use = true #with/without text to voice
sfx = 'Zzzzzzzzzzzzz' #use text to voice

#Timing
[timing] 
telegraph_time = 0 #1st step, time in seconds
attack_duration = 3
