type = 'Ranged'

#Weapon Details
[weapon]
name = 'Tangentializer'
flavor_text = 'What were we doing?'
mesh = ''

#Technical Specifications
[attack_info]
attach_point = 'right hand'
ammo = 20
attack_template = 'square'
projectile_spawn_location = [2, 100] #grids in front of you, grids above you
attack_radius = [15, 15, 15] # height and width 
can_move = false
can_charge = false
invulnerable_during = false
terrain_destructor = true
projectile_dmg = 75
collision_dmg = 75
velocity = 10 #meters per second? 

[effects]
particle_effect = 'meteor'
sfx_on_use = true #with/without text to voice
sfx = 'fire trailing' 

#Timing
[timing] 
telegraph_time = 5 #1st step, time in seconds
attack_duration = 7
