type = 'Melee/Ranged'

#Weapon Details
[weapon]
name = 'One Punch Fist'
flavor_text = 'One Serious Punch'

#Technical Specifications
[attack_info]
attach_point = 'right hand'
ammo = 1
attack_template = 'cylinder'
attack_radius = [100, 10] # height and width, the formula is V = (pi)(r)^(2)(h) 
can_move = false
invulnerable_during = true
terrain_destructor = true
projectile_dmg = 100
collision_dmg = 9001

[effects]
particle_effect = ''
sfx_on_use = true #with/without text to voice
sfx = 'Serious Punch'

#Timing
[timing] 
telegraph_time = 3 #1st step, time in seconds
attack_duration = 6
