type = 'Ranged'

#Weapon Details
[weapon]
name = 'Tangentializer'
flavor_text = 'What were we doing?'

#Technical Specifications
[attack_info]
attach_point = 'right hand'
ammo = 20
attack_template = 'square'
projectile_spawn_location = 2 #grids in front of you
attack_radius = [2, 2, 0] # height and width 
can_move = true
can_charge = false
invulnerable_during = false
terrain_destructor = false
projectile_dmg = 5
collision_dmg = 5
velocity = 2 #meters per second? 
[effects]
particle_effect = 'gyfycat.jpg'
sfx_on_use = true #with/without text to voice
sfx = 'Woooooo' #use text to voice

#Timing
[timing] 
telegraph_time = 0 #1st step, time in seconds
attack_duration = 1
